# Generated by Django 4.2 on 2024-06-11 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0001_initial'),
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='recipients',
            field=models.ManyToManyField(to='recipient.recipient', verbose_name='Получатели'),
        ),
        migrations.AddField(
            model_name='mailingstatus',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipient.recipient', verbose_name='клиент рассылки'),
        ),
    ]
